sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    # decrypting the service-account.json.
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    # installing Google Cloud SDK
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
    # Installing Kubectl in our SDK
  - gcloud components update kubectl
    # Authenticating our Service Account with the SDK
  - gcloud auth activate-service-account --key-file service-account.json
  
    # Configurating gcloud to work with our Kubernetes Cluster
  - gcloud config set project multi-k8s-407301
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster

    # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # Building the Client Test Image using our Development Dockerfile
  - docker build -t bryantto08/react-test -f ./client/Dockerfile.dev ./client

script:
    # Running Test Scripts
  - docker run -e CI=true bryantto08/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master